server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cafectrl_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   # options: create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  application:
    name: bookings

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Optional - if you plan login with JWT later
jwt:
  secret: your-very-secure-secret-key-12345678
  expiration-ms: 86400000

# Super Admin Defaults
app:
  super-admin:
    email: admin@admin.com
    password: admin

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}